Feature/create user
f-lab-edu/carrotbay pull request #2
Opened 2024-12-03 14:16 UTC by leemanbokgoo

## PR 타입
- feat : 회원가입
- feat : 닉네임 중복검사
- feat : 로그인

## 작업 내용
- 회원가입 기능 구현
- 회원가입시 닉네임 중복 검사 
- 아이디 중복 확인
- HttpSession 로그인 기능 구현
- 위의 작업에 관련된 테스트 구현

2025-02-23 08:47 UTC, f-lab-jd requested changes
고생하셨습니다! 리뷰 드린 내용 한번 확인 부탁드립니다. 

1. gitignore
2. 포맷터 
3. 주석 설명 

위 세가지는 전반적으로 확인이 필요합니다.

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/common/exception/CustomValidationException.java
> +public class CustomValidationException extends RuntimeException {
CustomValidationException 이 필요한 이유가 무엇인가요~?

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/common/handler/CustomExceptionHandler.java
> +@RestControllerAdvice
저희가 정했던 것 처럼 어노테이션에 설명 및 동작원리가 추가되면 좋을 것 같습니다.

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/common/handler/aop/CustomValidationAdvice.java
> +public class CustomValidationAdvice {
AOP 를 적용하신 이유가 무엇인가요~?

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/domain/user/User.java
> +	private UserStatus status;
일관성있게 `Column` 어노테이션을 추가하는게 좋겠습니다.

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/domain/user/UserController.java
> +@RequestMapping("/api/user") // "/api/user" 경로로 들어오는 요청을 해당 메서드로 매핑하는 Spring MVC의 요청 처리 어노테이션
Restful API URL 규칙에 맞게 재정의가 필요합니다.

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/domain/user/UserController.java
> +	private static int SESSEION_TIME = 60 * 30;
상수로 잘 빼셨습니다 👍

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/domain/user/UserController.java
> +	public ResponseEntity<?> register(
응답타입을 `<?>`  로 하신이유가 있으신가요? 이렇게 했을때 어떤일이 벌어지나요~?

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/domain/user/UserService.java
> +		// 닉네임 중복 검사
불필요한 주석은 제거해주어도 좋습니다. 주석없이도 잘 읽히는 코드가 좋은 코드입니다~!

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/domain/user/UserService.java
> +		if(BCrypt.checkpw(loginRequestDto.getPassword(), loginUser.getPassword())) {
코드 전반적으로 포맷팅에 대한 일관성 점검이 필요합니다.

2025-02-23 08:47 UTC, f-lab-jd commented on src/main/java/com/carrotbay/domain/user/dto/UserDto.java
> +    public static class RegisterUserDto{
책임을 잘 분리해주셨습니다 👍

2025-02-28 15:23 UTC, leemanbokgoo commented on src/main/java/com/carrotbay/common/exception/CustomValidationException.java
> +public class CustomValidationException extends RuntimeException {
CustomValicationException은 유효성 검사 시, 에러 메세지를 반환하기위해서 만들어진 클래스입니다. 기존의 자바 exception 클래스로는 아래와 같은 데이터 구조로 response를 보낼 수가 없어서 CustomException 클래스를 구현 할 필요성이 있다고 판단했습니다.
{
    "password": "8~20자 사이에 영대소문자와 특수문자를 하나 이상 포함해야 합니다.",
    "username": "이메일을 입력해주세요."
}

2025-02-28 15:26 UTC, leemanbokgoo commented on src/main/java/com/carrotbay/domain/user/UserController.java
> +	public ResponseEntity<?> register(
ResponseEntity를 사용해 클라이언트에 데이터를 반환할때, 데이터의 타입이 String 일지 Dto 객체일지 알수없어서 ResponseEntity<?>를 사용했습니다.

?는 제네릭 타입을 나타내며 제네릭 타입으로 어떤 타입이든 받을 수 있도록 허용합니다. 그렇기떄문에 유연하게 데이터를 반환할 수 있지만 타입 안정성이 부족해서 의도하지않은 객체 타입이 반환 될 수 있습니다. 또한 어떤 타입이 반환 될지 명확하지않기떄문에 코드의 의도를 파악하기 어려울 수 있습니다.

2025-02-28 15:28 UTC, leemanbokgoo commented on src/main/java/com/carrotbay/common/handler/aop/CustomValidationAdvice.java
> +public class CustomValidationAdvice {
해당 코드는 put과 post 요청이 들어왔을때 유효성 검사를 진행하고 유효성 검사에 실패했을때 에러 메세지를 반환하기 위한 클래스입니다. 메소드 단위에서 이루워지는 유효성 검사를 공통의 관심사로 분류하고 중복 코드를 제거하기위해 적용하였습니다.

2025-03-02 11:06 UTC, f-lab-jd approved these changes
👍

2025-03-03 09:36 UTC, merged